version: '3.4'
services:
  netbox:
    ports:
    - 8002:8080
    volumes:
    - /docker/netbox:/etc/netbox/config:z,ro
    - /docker/netbox-media-files:/opt/netbox/netbox/media:z,rw
    - /docker/netbox-reports-files:/opt/netbox/netbox/reports:z,rw
    - /docker/netbox-scripts-files:/opt/netbox/netbox/scripts:z,rw
    healthcheck:
      retries: 15
  netbox-worker:
    volumes:
    - /docker/netbox:/etc/netbox/config:z,ro
    - /docker/netbox-media-files:/opt/netbox/netbox/media:z,rw
    - /docker/netbox-reports-files:/opt/netbox/netbox/reports:z,rw
    - /docker/netbox-scripts-files:/opt/netbox/netbox/scripts:z,rw
  netbox-housekeeping:
    volumes:
    - /docker/netbox:/etc/netbox/config:z,ro
    - /docker/netbox-media-files:/opt/netbox/netbox/media:z,rw
    - /docker/netbox-reports-files:/opt/netbox/netbox/reports:z,rw
    - /docker/netbox-scripts-files:/opt/netbox/netbox/scripts:z,rw
